library(quantmod)
library(tseries)
library(timeSeries)
library(forecast)
library(xts)
getSymbols('XU100_IS', from= '2011-01-03', to= '2020-12-31')
class(XU100_IS)
XU100_IS_Close_Prices = XU100_IS[,5]
plot(XU100_IS_Close_Prices)
par(mfrow=c(1,1))
Acf(XU100_IS_Close_Prices, main= 'ACF for Differenced Series' )
Pacf(XU100_IS_Close_Prices, main= 'PACF for Differenced Series')
print(adf.test(XU100_IS_Close_Prices, seasonal = FALSE))
fitA = tsdisplay(residuals(fitA), lag.max=40, main='(1,1,3) Model Residuals')
auto.arima(XU100_IS_Close_Prices, seasonal = FALSE)
fitB = arima(XU100_IS_Close_Prices, order= c(1,1,18))
tsdisplay(residuals(fitB), lag.max=40, main= '(1,1,18) Model Residuals')
fitC = arima(XU100_IS_Close_Prices, order=c(1,2,38))
tsdisplay(residuals(fitC), lag.max=40, main= '(1,2,38 Model Residuals')
fitD = arima(XU100_IS_Close_Prices, order=c(1,1,1))
tsdisplay(residuals(fitD), lag.max=40, main='(1,1,1) Model Residuals')
par(mfrow=c(2,2))
term<-100
fcast1 <- forecast(fitA, h=term)
plot(fcast1)
fcast2 <- forecast(fitB, h=term)
plot(fcast2)
fcast3 <- forecast(fitC, h=term)
plot(fcast3)
fcast4 <- forecast(fitD, h=term)
plot(fcast4)
accuracy(fcast1)
accuracy(fcast2)
accuracy(fcast3)
accuracy(fcast4)
term<-45
fcast1 <- forecast(fitA, h=term)
plot(fcast1)
fcast2 <- forecast(fitB, h=term)
plot(fcast2)
fcast3 <- forecast(fitC, h=term)
plot(fcast3)
fcast4 <- forecast(fitD, h=term)
plot(fcast4)
term<-365
fcast1 <- forecast(fitA, h=term)
plot(fcast1)
fcast2 <- forecast(fitB, h=term)
plot(fcast2)
fcast3 <- forecast(fitC, h=term)
plot(fcast3)
fcast4 <- forecast(fitD, h=term)